local t = Def.ActorFrame{
  Def.Actor{
    OnCommand=cmd(sleep,0.3);
  };
};

t[#t+1] = Def.ActorFrame{
  LoadActor("_swoosh.ogg")..{
    StartTransitioningCommand=cmd(sleep,1;queuecommand,"Play");
    PlayCommand=cmd(play)
  };
  Def.Quad{
    InitCommand=cmd(FullScreen;diffuse,color("0,0,0,1"));
    OnCommand=cmd(diffusealpha,0;sleep,1;linear,0.3;diffusealpha,1;)
  };
  LoadActor("stagetemp/loadf_0u")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-128);
    OnCommand=cmd(addy,-224;sleep,1;linear,0.2;addy,224;);
  };
  LoadActor("stagetemp/loadf_0d")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+128);
    OnCommand=cmd(addy,224;sleep,1;linear,0.2;addy,-224;);
  };
  LoadActor("stagetemp/loadf_1u")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-148);
    OnCommand=cmd(addy,-184;sleep,1;bounceend,0.3;addy,184;);
  };
  LoadActor("stagetemp/loadf_1d")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+148);
    OnCommand=cmd(addy,184;sleep,1;bounceend,0.3;addy,-184;);
  };
  LoadActor("stagetemp/loadf_3u")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-208);
    OnCommand=cmd(addy,-64;sleep,1;bounceend,0.3;addy,64;);
  };
  LoadActor("stagetemp/loadf_3d")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+208);
    OnCommand=cmd(addy,64;sleep,1;bounceend,0.3;addy,-64;);
  };
  LoadActor("stagetemp/loadf_2u")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-112);
    OnCommand=cmd(addx,-640;zoomy,0;sleep,1;linear,0.2;zoomy,1;addx,640;);
  };
  LoadActor("stagetemp/loadf_2d")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+112);
    OnCommand=cmd(addx,640;zoomy,0;sleep,1;linear,0.2;zoomy,1;addx,-640;);
  };
  LoadActor("stagetemp/box.txt")..{
    InitCommand=cmd(effectmagnitude,0,100,0;CenterY;x,SCREEN_CENTER_X-136;z,16);
    OnCommand=cmd(rotationy,-360;zoom,0;sleep,1;linear,0.2;zoom,1;rotationy,0;);
  };
  LoadActor("stagetemp/box.txt")..{
    InitCommand=cmd(effectmagnitude,0,100,0;CenterY;x,SCREEN_CENTER_X+136;z,16);
    OnCommand=cmd(rotationy,-360;zoom,0;sleep,1;linear,0.2;zoom,1;rotationy,0;);
  };
  LoadActor("stagetemp/loadf_4c")..{
    InitCommand=cmd(Center;rainbow,true);
    OnCommand=cmd(diffusealpha,0;sleep,1;linear,0.2;diffusealpha,1;);
  };
};

return t;
