return Def.ActorFrame{
	Def.Quad{
    InitCommand=cmd(FullScreen;diffuse,color("0,0,0,1"));
  };
  LoadActor("stagetemp/loadf_0u")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-128);
  };
  LoadActor("stagetemp/loadf_0d")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+128);
  };
  LoadActor("stagetemp/loadf_1u")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-148);
  };
  LoadActor("stagetemp/loadf_1d")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+148);
  };
  LoadActor("stagetemp/loadf_3u")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-208);
  };
  LoadActor("stagetemp/loadf_3d")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+208);
  };
  LoadActor("stagetemp/loadf_2u")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-112);
  };
  LoadActor("stagetemp/loadf_2d")..{
    InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y+112);
  };
  LoadActor("stagetemp/box.txt")..{
    InitCommand=cmd(effectmagnitude,0,100,0;CenterY;x,SCREEN_CENTER_X-136;z,16);
  };
  LoadActor("stagetemp/box.txt")..{
    InitCommand=cmd(effectmagnitude,0,100,0;CenterY;x,SCREEN_CENTER_X+136;z,16);
  };
  LoadActor("stagetemp/loadf_4c")..{
    InitCommand=cmd(Center;rainbow,true);
  };
};
